snapperd_snapshot_var.pp:
	checkmodule -m snapperd_snapshot_var.te -o snapperd_snapshot_var.mod
	semodule_package -m snapperd_snapshot_var.mod -o snapperd_snapshot_var.pp
	rm snapperd_snapshot_var.mod
